name: Deploy to Firebase Hosting on Push
'on':
  push:
    branches:
      - main  # Cambia "main" por el nombre de la rama en la que deseas que se active el despliegue automático

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Build application
        run: npm run build

      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_TAREAS_APP_1286B }}'
          projectId: tareas-app-1286b
          channelId: <tareas-app-23>
